services:
  - type: web
    name: oficina-wvl
    env: python
    rootDir: WVL_web
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: WVL_DATA_DIR
        value: /var/data/data
      - key: WVL_PDF_DIR
        value: /var/data/orcamentos
    disk:
      name: wvl-data
      mountPath: /var/data
      sizeGB: 1
